# Generated by Django 4.0.4 on 2022-06-17 17:16

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default='profile_pic/user', max_length=255, verbose_name='profile_pic/'),
        ),
        migrations.CreateModel(
            name='NeighbourHood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=60)),
                ('hood_logo', cloudinary.models.CloudinaryField(default='profile_pic/user', max_length=255, verbose_name='hood_pic/')),
                ('description', models.TextField()),
                ('health_tell', models.IntegerField(blank=True, null=True)),
                ('health_officer', models.CharField(blank=True, max_length=60, null=True)),
                ('police_tell', models.IntegerField(blank=True, null=True)),
                ('police_officer', models.CharField(blank=True, max_length=60, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hood', to='hood.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='neighbourhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='hood.neighbourhood'),
        ),
    ]
